# Generated by Django 4.1.7 on 2023-05-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_labeling", "0005_alter_autolabelingconfig_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autolabelingconfig",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("Category", "category"),
                    ("Span", "span"),
                    ("Text", "text"),
                    ("Relation", "relation"),
                    ("SpanRelAndTrait", "spanRelAndTrait"),
                ],
                max_length=100,
            ),
        ),
    ]
