# Generated by Django 4.1.7 on 2023-05-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_imagecaptioningproject_alter_project_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sequencelabelingproject",
            name="use_trait",
            field=models.BooleanField(default=False),
        ),
    ]
