# Generated by Django 4.1.7 on 2023-05-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0017_trait"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trait",
            old_name="label_id",
            new_name="entity_id",
        ),
    ]
