# Generated by Django 4.1.7 on 2023-05-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0018_rename_label_id_trait_entity_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="boundingbox",
            name="state",
            field=models.CharField(
                choices=[("auto", "Auto"), ("added", "Added"), ("modified", "Modified"), ("removed", "Removed")],
                default="added",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="state",
            field=models.CharField(
                choices=[("auto", "Auto"), ("added", "Added"), ("modified", "Modified"), ("removed", "Removed")],
                default="added",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="relation",
            name="state",
            field=models.CharField(
                choices=[("auto", "Auto"), ("added", "Added"), ("modified", "Modified"), ("removed", "Removed")],
                default="added",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="segmentation",
            name="state",
            field=models.CharField(
                choices=[("auto", "Auto"), ("added", "Added"), ("modified", "Modified"), ("removed", "Removed")],
                default="added",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="span",
            name="state",
            field=models.CharField(
                choices=[("auto", "Auto"), ("added", "Added"), ("modified", "Modified"), ("removed", "Removed")],
                default="added",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="textlabel",
            name="state",
            field=models.CharField(
                choices=[("auto", "Auto"), ("added", "Added"), ("modified", "Modified"), ("removed", "Removed")],
                default="added",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="trait",
            name="state",
            field=models.CharField(
                choices=[("auto", "Auto"), ("added", "Added"), ("modified", "Modified"), ("removed", "Removed")],
                default="added",
                max_length=10,
            ),
        ),
    ]
