# Generated by Django 4.1.7 on 2023-05-16 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0018_rename_label_id_trait_entity_id"),
        ("data_export", "0004_exportedcomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportedTrait",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labels.trait",),
        ),
    ]
